---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lodging
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`) || PathPrefix(`/lodging`)
      middlewares:
        - name: lodging-stripprefix
      priority: 10
      services:
        - kind: Service
          name: lodging
          port: 80
